### ISSUE TITLE
Pin express.js to 3.* in dstore/package.json

### ISSUE THREAD

**Issue by andylolz** [devinit/D-Portal#358]
I could very well be wrong about this! But…

It appears dstore/serv.js is not yet compatible with express.js 4.*? Here’s an error message:

```sh
$ node js/serv.js
/d-portal/dstore/node_modules/express/lib/express.js:99
      throw new Error('Most middleware (like ' + name + ') is no longer bundled with Express and must be installed separately. Please see https://github.com/senchalabs/connect#middleware.');
      ^

Error: Most middleware (like json) is no longer bundled with Express and must be installed separately. Please see https://github.com/senchalabs/connect#middleware.
    at Function.get (/d-portal/dstore/node_modules/express/lib/express.js:99:13)
    at Object.<anonymous> (/d-portal/dstore/js/serv.js:21:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
```

If that’s the case, it would be best to pin the version of express to 3.* in https://github.com/devinit/D-Portal/blob/daffbc51/dstore/package.json#L11

**Comment by Mattdevinit** [comment]
thanks @andylolz for flagging this (and note on #306)!  will investigate both further and update this as required

**Comment by notshi** [comment]
Hi @andylolz, thanks very much for this - it should be fixed now.
