### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by tobybatch** [devinit/D-Portal#407]
I trying to start dportal and I have this error.

```
root@6fda545444fd:/opt/D-Portal# /opt/D-Portal/bin/serv --port=8011
/opt/D-Portal/dportal/node_modules/express-fileupload/lib/index.js:137
        mv: function(path, callback = null) {
                                    ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/opt/D-Portal/dportal/js/serv.js:5:26)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
root@6fda545444fd:/opt/D-Portal#
```

The build process is here https://github.com/NeonOpenAG/AG/blob/develop/dockers/dportal/Dockerfile

**Comment by xriss** [comment]
looks like node dependencies are missing, try running the ./install_deps script to make sure everything is setup.

**Comment by tobybatch** [comment]
I ran the install_deps and I still have the error.
```
root@6fda545444fd:/opt/D-Portal# ./install_deps
--- snip ---
  +-- string-width@2.1.1
  | +-- is-fullwidth-code-point@2.0.0
  | `-- strip-ansi@4.0.0
  |   `-- ansi-regex@3.0.0
  +-- which-module@2.0.0
  +-- y18n@3.2.1
  `-- yargs-parser@7.0.0

root@6fda545444fd:/opt/D-Portal# /opt/D-Portal/bin/serv --port=8011
/opt/D-Portal/dportal/node_modules/express-fileupload/lib/index.js:137
        mv: function(path, callback = null) {
                                    ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/opt/D-Portal/dportal/js/serv.js:5:26)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
root@6fda545444fd:/opt/D-Portal#
```

**Comment by xriss** [comment]
could be a node / module incompatibility issue, this whole node modules thing is a rather unstable DLL hell.

Have you tried different versions of node? NVM works, mostly.

https://github.com/creationix/nvm

Could be caused by multiple versions of node arguing as well.

Node is fun.

I'll check that it is still working on mine and give you some version numbers that it does run on...

**Comment by xriss** [comment]
Still working OK for me, my installed versions of node are

node --version
v4.7.2

npm --version
3.5.2

This is using the node/npm from debian/ubuntu packages so it is a slightly older version but seems to be a safer bet than using bleeding edge versions.

**Comment by tobybatch** [comment]
I still get the same error.  If you guys are on *nix (linux or mac) and you want to check the environment you can run it with:

    docker run -ti openagdata/dportal```

This will drop you into the docker at a bash shell.

I've run 
```
root@74db9dadd4c2:/opt/D-Portal# ./install_deps
--- snip ---
  +-- string-width@2.1.1
  | +-- is-fullwidth-code-point@2.0.0
  | `-- strip-ansi@4.0.0
  |   `-- ansi-regex@3.0.0
  +-- which-module@2.0.0
  +-- y18n@3.2.1
  `-- yargs-parser@7.0.0
root@74db9dadd4c2:/opt/D-Portal# node --version
v4.7.2
root@74db9dadd4c2:/opt/D-Portal# npm --version
3.5.2
root@74db9dadd4c2:/opt/D-Portal# ./bin/serv
/opt/D-Portal/dportal/node_modules/express-fileupload/lib/index.js:137
        mv: function(path, callback = null) {
                                    ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/opt/D-Portal/dportal/js/serv.js:5:26)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
root@74db9dadd4c2:/opt/D-Portal#
```

**Comment by tobybatch** [comment]
@xriss Some success

I just tried latest node, v6.11.3 and the server starts but I get 

```
This page isn’t working

localhost redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS
```

I've cleared cookies.

**Comment by tobybatch** [comment]
I also get the same issue install on my native system, Ubuntu 17.04.  Which OS version are you on? I can move the docker to that easily.

using instructions at https://github.com/devinit/D-Portal/blob/master/documents/ctrack_localtest.md

**Comment by tobybatch** [comment]
Interestingly if I start dportal with  v4.7.2 and --harmony the server starts and I get the redirect error.

**Comment by xriss** [comment]
Redirect error sounds like you may have not built the static site, did you run

	dportal/build

this will generate all of the static pages and gets auto called by the ./serv script in root, if you start the server any other way then this needs to be called at least once.

**Comment by tobybatch** [comment]
w00t! That's it.

Thanks Kriss, new docker on the way.
